{
  parserClass="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.IJavaParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="IJava"
  psiImplClassSuffix="Impl"
  psiPackage="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model"
  psiImplPackage="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.impl"

  elementTypeHolderClass="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.IJavaTypes"
  elementTypeClass="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.IJavaElementType"
  tokenTypeClass="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.IJavaTokenType"

  psiImplUtilClass="edu.rit.cs.plcc.jetbrainsPlugin.lang.ijava.parser_model.impl.IJavaPsiImplUtil"
}

ijavaFile ::= javaCodeBlock*
javaCodeBlock ::= GRAMMAR_NAME_CLASS_NAME CODE_BLOCK_BOUNDARY JAVA_LINE+ CODE_BLOCK_BOUNDARY
